### ISSUE TITLE
add shortcut to manipulate the dialog

### ISSUE THREAD

**Issue by cmeriaux** [young-developer/nppNavigateTo#10]
Could you add some shortcuts to manipulate faster the dialog : 

ctrl+a : select all the text already written in the dialog
ctrl+arrow left/rigth: move previous/next word
ctrl + shift + arrow left/right: slect the previous/next word
....

thanks

**Comment by young-developer** [comment]
@cmeriaux CTRL+A was restored. I am investigating another short cuts.

**Comment by ajason08** [comment]
Hi, thank you for you great work here!
I have a little and related request I think can benefit users like me.

**The story:** when I open the NavigateTo dialog almost always I have to press **ctrl+a** to delete the text and change destination (because with many tabs most probably the destination is different).
**Request:** can you please set the dialog to enter with fully selection (**ctrl+a**) or adding some option for setting it as default?
Then, if one wants the same last destination, one goes pressing enter; if different just start typing the new one

Similarly, but less frequent, be able to use **_home_** and **_end_** keys, or **_ctrl+arrow_** would be nice too.

Thank you very much!

**Comment by young-developer** [comment]
https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.7
