### ISSUE TITLE
Nothing happens when press Enter

### ISSUE THREAD

**Issue by anki-code** [young-developer/nppNavigateTo#11]
Hi! Thank you for your great work!

I've tried the version v.1.12.4 (64) and when I press Enter key the file isn't open.

Details:
1. Windows 10, Notepad++ 7.5.5 (64), NavigateTo v.1.12.4 (64)
2. Press `Ctrl+,` and choose any file (press Enter or click)
3. Nothing happens

**Comment by doriancuentas** [comment]
Same here

**Comment by regis92** [comment]
Same here :-(
Windows 10, Notepad++ 7.5.7 (64), NavigateTo v.1.12.4 (64)

**Comment by regis92** [comment]
Great, that's OK for me !
    
    THX A LOT :-)
    
    
    Le 06/07/2018 à 12:26, Oleksii
      Maryshchenko a écrit :
    
    
      @anki-code
        @doriancuentas
        @regis92
        I update x64 release dll - https://github.com/young-developer/nppNavigateTo/releases/tag/1.12.4.
        Please download and test it.
        Thank you for you feedback.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/young-developer/nppNavigateTo","title":"young-developer/nppNavigateTo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/young-developer/nppNavigateTo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@young-developer in #11: @anki-code @doriancuentas @regis92 I update x64 release dll - https://github.com/young-developer/nppNavigateTo/releases/tag/1.12.4.\r\nPlease download and test it.\r\nThank you for you feedback. "}],"action":{"name":"View Issue","url":"https://github.com/young-developer/nppNavigateTo/issues/11#issuecomment-402995090"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/young-developer/nppNavigateTo/issues/11#issuecomment-402995090",
"url": "https://github.com/young-developer/nppNavigateTo/issues/11#issuecomment-402995090",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [young-developer/nppNavigateTo] Nothing happens when press Enter (#11)",
"sections": [
{
"text": "",
"activityTitle": "**Oleksii Maryshchenko**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@young-developer",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"young-developer/nppNavigateTo\",\n\"issueId\": 11,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"young-developer/nppNavigateTo\",\n\"issueId\": 11\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/young-developer/nppNavigateTo/issues/11#issuecomment-402995090"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 314134269\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by young-developer** [comment]
Please check the latest version: https://github.com/young-developer/nppNavigateTo/releases/tag/v.1.12.6
